### ISSUE TITLE
panic in `transport_tcp_concurrent` on windows on github CI

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1176]
### Describe the release item

The test `transport_tcp_concurrent` in github CI on windows panics with message 
```
thread 'transport_tcp_concurrent' panicked at io\zenoh-transport\tests\unicast_concurrent.rs:316:43:
called `Result::unwrap()` on an `Err` value: error scheduling message! at io\zenoh-transport\src\unicast\universal\transport.rs:408.
```
see windows run, line 2785, https://github.com/eclipse-zenoh/zenoh/actions/runs/9588701994/job/26441248363

The failure occurs only if test is executed separately from other tests, otherwise it's just terminated by timeout.
The PR for testing this: https://github.com/eclipse-zenoh/zenoh/pull/1172

I was unable to reproduce this locally

**Comment by milyin** [comment]
![image](https://github.com/eclipse-zenoh/zenoh/assets/1909657/e3836ada-7b3a-4f48-a544-ff2245c7f206)

**Comment by Mallets** [comment]
It seems the CI has been happy for a while now and the test didn't fail anymore.
Closing the issue. Feel free to reopen it if it's still relevant.
