### ISSUE TITLE
`zenohd` panics with `plugins_loading/enabled:false`

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#1235]
### Describe the bug

If the `plugins_loading/enabled` configuration option is set to `false`, then `zenohd` panics because the plugin loader is initialized with an empty search path:

https://github.com/eclipse-zenoh/zenoh/blob/b3e42cef38f6227a87a26725d0479bcf9ace69a9/commons/zenoh-config/src/lib.rs#L732-L742

Here is the error:

```
2024-07-10T08:42:14.363618Z  INFO main ThreadId(01) zenoh::api::loader: Loading required plugin "rest"
thread 'main' panicked at zenoh/src/api/loader.rs:64:17:
Plugin load failure: Library file 'libzenoh_plugin_rest.dylib' not found at commons/zenoh-util/src/lib_loader.rs:145.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To reproduce

1. `cargo run --bin zenohd -- --cfg='plugins_loading/enabled:false'`

### System info

- ref: [9e1c4a8680a04b34f09dd2776d07958c8aae6f92](https://github.com/eclipse-zenoh/zenoh/commit/9e1c4a8680a04b34f09dd2776d07958c8aae6f92)

**Comment by Mallets** [comment]
Fixed by #1269
