### ISSUE TITLE
zenohd default config error

### ISSUE THREAD

**Issue by Sobczaczek** [eclipse-zenoh/zenoh#1292]
### Describe the bug

While running zenohd with default (DEFAULT_CONFIG.json5) config -> error:
INFO main ThreadId(01) zenohd: zenohd v1.0.0-alpha.5 built with rustc 1.75.0 (82e1608df 2023-12-21)
thread 'main' panicked at zenohd/src/main.rs:122:42:
called `Result::unwrap()` on an `Err` value: JSON error: invalid type: string "", expected a list of whatami variants ('router', 'peer', 'client') at commons/zenoh-config/src/lib.rs:748.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### To reproduce

1. zenohd -c DEFAULT_CONFIG.json5 

### System info

- Ubuntu 24.04

**Comment by anhaabaete** [comment]
Please, test it.

https://github.com/eclipse-zenoh/zenoh/compare/main...anhaabaete:zenoh:patch-1

it work to me.

**Comment by milyin** [comment]
The approach used for fixing this seems to be wrong, we need to correct DEFAULT_CONFIG or provide default value for this parameter. See discussion in https://github.com/eclipse-zenoh/zenoh/pull/1326
Going to revert the fix
